apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .AddonName }}-{{ .Cluster }}
rules:
- apiGroups: ["workload.kcp.dev"]
  resources: ["workloadclusters"]
  resourceNames: [{{ .Cluster }}]
  verbs: ["sync"]
- apiGroups: ["workload.kcp.dev"]
  resources: ["workloadclusters/status"]
  resourceNames: [{{ .Cluster }}]
  verbs: ["update", "patch"]
- apiGroups: ["workload.kcp.dev"]
  resources: ["workloadclusters"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiresource.kcp.dev"]
  resources: ["apiresourceimports"]
  verbs: ["get", "create", "update", "delete", "list", "watch"]